name:
description: Programming and computer sciences
meta_description: "Blogging, programming languages, stuff"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://alvarezariel.github.io'
google_analytics: 'UA-62262146-2'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'alvarezariel.github.io'
author:         'Ariel Alvarez'

